
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'rightIDIFWHILETYPErightASSIGNleftLTLTEGTGTEleftPLUSMINUSleftMODDIVENTTIMESDIVIDEleftEXPleftLPARENTRPARENTASSIGN BLINK BOOKED COMMA CONST DELETE DIVENT DIVIDE DOT ELSE EXP F FALSE FOR GLOBAL GT GTE ID IF INSERT INT LCORCH LEN LENGHTERROR LPARENT LT LTE MINUS MOD NE NEG PARENTCL PARENTCR PLUS PROCEDURE RANGE RCORCH RPARENT SEMICOLON T TIMES TP TRUE TYPE VARERROR WHILEprogram : statement statement : assignment functionassignment : ID ASSIGN term SEMICOLON statementassignment : ID COMMA ID ASSIGN term COMMA term SEMICOLON statementassignment : emptyfunction : typefunction : emptytype : TYPE LPARENT ID RPARENT SEMICOLON statementterm : FALSEterm : TRUEterm : factorfactor : IDfactor : INTempty : '
    
_lr_action_items = {'ID':([0,10,11,12,21,22,26,27,30,],[4,13,19,20,4,13,4,13,4,]),'TYPE':([0,3,5,6,7,8,21,24,26,28,30,31,],[-14,9,-5,-2,-6,-7,-14,-3,-14,-8,-14,-4,]),'$end':([0,1,2,3,5,6,7,8,21,24,26,28,30,31,],[-14,0,-1,-14,-5,-2,-6,-7,-14,-3,-14,-8,-14,-4,]),'ASSIGN':([4,19,],[10,22,]),'COMMA':([4,13,15,16,17,18,25,],[11,-12,-9,-10,-11,-13,27,]),'LPARENT':([9,],[12,]),'FALSE':([10,22,27,],[15,15,15,]),'TRUE':([10,22,27,],[16,16,16,]),'INT':([10,22,27,],[18,18,18,]),'SEMICOLON':([13,14,15,16,17,18,23,29,],[-12,21,-9,-10,-11,-13,26,30,]),'RPARENT':([20,],[23,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'statement':([0,21,26,30,],[2,24,28,31,]),'assignment':([0,21,26,30,],[3,3,3,3,]),'empty':([0,3,21,26,30,],[5,8,5,5,5,]),'function':([3,],[6,]),'type':([3,],[7,]),'term':([10,22,27,],[14,25,29,]),'factor':([10,22,27,],[17,17,17,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> statement','program',1,'p_program','Parser.py',21),
  ('statement -> assignment function','statement',2,'p_statement','Parser.py',25),
  ('assignment -> ID ASSIGN term SEMICOLON statement','assignment',5,'p_simpleAssignment','Parser.py',29),
  ('assignment -> ID COMMA ID ASSIGN term COMMA term SEMICOLON statement','assignment',9,'p_doubleAssignment','Parser.py',33),
  ('assignment -> empty','assignment',1,'p_assignmentEmp','Parser.py',37),
  ('function -> type','function',1,'p_function','Parser.py',41),
  ('function -> empty','function',1,'p_functionEmp','Parser.py',45),
  ('type -> TYPE LPARENT ID RPARENT SEMICOLON statement','type',6,'p_type','Parser.py',48),
  ('term -> FALSE','term',1,'p_term0','Parser.py',52),
  ('term -> TRUE','term',1,'p_term1','Parser.py',56),
  ('term -> factor','term',1,'p_term2','Parser.py',60),
  ('factor -> ID','factor',1,'p_factor0','Parser.py',64),
  ('factor -> INT','factor',1,'p_factor1','Parser.py',68),
  ('empty -> <empty>','empty',0,'p_empty','Parser.py',72),
]
